site_name: Atlassian Plugin Remote Install
repo_url: https://github.com/itdevsamurai/atlassian-plugin-remote-install
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    logo: material/tools
  favicon: images/favicon.png
  font:
    text: Open Sans
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - mkdocs-click
  - attr_list
  - toc:
      permalink: ⚓︎
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences

plugins:
  - include-markdown
